# Generated by Django 4.0.4 on 2022-05-28 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
