# Generated by Django 4.0.4 on 2022-08-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_comment_approved_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
